name: nexgaze
description: "Smart Glasses NexGaze"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.0
  fl_chart: ^0.64.0
  flutter_compass: ^0.8.0
  cupertino_icons: ^1.0.8
  pedometer: ^4.0.1
  permission_handler: ^11.0.1  # AGGIUNTO per gestione permessi runtime
  video_player: ^2.7.0
  flutter_blue_plus: ^1.3.4

  neurosdk2: ^1.0.17
  em_st_artifacts: ^1.0.1
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: 2.1.0
  flutter_tts: ^3.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"  # <--- icona NexGaze(1024x1024)

flutter:
  uses-material-design: true

  assets:
    - assets/icons/sun.png
    - assets/icons/rain.png
    - assets/icons/cloud.png
    - assets/icons/compass_arrow.png
    - assets/icons/hiking.png
    - assets/icons/running.png
    - assets/icons/cycling.png
    - assets/icons/skiing.png
    - assets/icons/yoga.png
    - assets/icons/relax.png
    - assets/images/nexgaze.png
    - assets/images/mode1.png
    - assets/images/mode2.png
    - assets/images/mode3.png
    - assets/images/mode4.png
    - assets/images/mode5.png
    - assets/images/mode6.png
    - assets/videos/forest.mp4
    - assets/videos/yoga.mp4
    - assets/images/nexgaze_logo.png

  fonts:
    - family: Downlink
      fonts:
        - asset: assets/fonts/Downlink.otf